Repository tim-balloon/TIMflight, pull requests merged in 2023-11, with the labels that each got.

#70 EtherCAT motors enhancements
  blast_config/derived.c
  blast_config/tx_struct_tng.c
  mcp/include/ec_motors.h
  mcp/include/motors.h
  mcp/motors/ec_motors.c
Labels: enhancement, Code Cleanup

#72 Add telemetry for EtherCAT application layer status codes
  blast_config/tx_struct_tng.c
  mcp/include/motors.h
  mcp/mcp.c
  mcp/motors/motors.c
Labels: enhancement

#65 [Groundhog] An EVTM listener implementation + basic testing framework
  blast_config/command_list.c
  blast_config/include/command_list.h
  common/bitserver.c
  common/include/bitserver.h
  groundhog/CMakeLists.txt
  groundhog/blast/CMakeLists.txt
  groundhog/blast/biphase.c
  groundhog/blast/decom_pci.h
  groundhog/blast/evtm.c
  groundhog/blast/groundhog.h
  groundhog/blast/highrate.c
  groundhog/blast/main.c
  groundhog/blast/pilot.c
  groundhog/blast/tests/CMakeLists.txt
  groundhog/blast/tests/test_gh_evtm.c
  groundhog/groundhog_funcs.c
  groundhog/groundhog_funcs.h
  groundhog/testing/clint.sh
  groundhog/testing/cpplint.py
  liblinklist/linklist.c
  mcp/commanding/commands.c
  mcp/communications/evtm.c
  mcp/communications/tests/test_evtm.c
  mcp/include/command_struct.h
Labels: enhancement, Code Cleanup, testing
