Repository tim-balloon/TIMflight, pull requests merged in 2024-09, with the labels that each got.

#127 FTS test flight: thermistor names, kst files, comments
  blast_config/derived.c
  kst/tim/elevation.kst
  kst/tim/gyros.kst
  kst/tim/starcam.kst
  kst/tim/thermistors.kst
  mcp/tx.c
Labels: PRE-FTSFLIGHT-MUSTFIX

#126 Fixes from FTS night testing night 1
  mcp/include/motors.h
  mcp/mcp.c
  mcp/sensors/acs.c
  mcp/sensors/star_camera_receive.c
  mcp/sensors/star_camera_transmit.c
Labels: enhancement, Code Cleanup

#128 Fixes in advance of FTS compatibility
  blast_etc/netplan/00-installer-config_fc1.yaml
  blast_etc/netplan/00-installer-config_fc2.yaml
  blast_etc/udev/91-serial.rules
  kst/tim/all_kst.sh
  kst/tim/azimuth.kst
  kst/tim/ec_motors.kst
  kst/tim/elevation.kst
  kst/tim/sip.kst
  mcp/include/star_camera_trigger.h
  mcp/sensors/acs.c
  mcp/sensors/csbf_dgps.c
  mcp/sensors/star_camera_transmit.c
  scripts/uploading/upload_linklists.sh
Labels: bug, enhancement

#130 Fix combined gyro rotation matrix typo caused by scientififc notation
  mcp/commanding/commands.c
  mcp/sensors/acs.c
Labels: bug

#132 gyro mask quality of life and scripts/kst updates/fixes
  blast_config/command_list.c
  blast_config/include/command_list.h
  blast_etc/hosts/hosts_fc1
  blast_etc/hosts/hosts_fc2
  blast_etc/systemd/starcam_software.service
  blast_etc/udev/zz-ueyeusbd.rules
  kst/tim/magnetometers.kst
  kst/tim/thermistors.kst
  mcp/CMakeLists.txt
  mcp/commanding/commands.c
  mcp/motors/motors.c
  mcp/sensors/dsp1760.c
  scripts/building/build_mcp.sh
  scripts/inflight/start_sc_soft.sh
  scripts/uploading/upload_etc.sh
Labels: enhancement

#133 Launch attempt #2 improvements
  blast_config/command_list.c
  blast_config/include/command_list.h
  blast_config/tx_struct_tng.c
  mcp/commanding/commands.c
  mcp/include/star_camera_trigger.h
  mcp/mcp.c
  mcp/pointing/pointing.c
  mcp/sensors/star_camera_trigger.c
Labels: bug, documentation

#136 starcam timeout update fix
  kst/tim/elevation.kst
  kst/tim/power_system.kst
  mcp/sensors/star_camera_trigger.c
  owl/owl-files/tim/tim2024.owl
Labels: bug, enhancement
