Repository tim-balloon/TIMflight, pull requests merged in 2024-08, with the labels that each got.

#102 Fix incorrect gyro bias estimation algorithm - sin/cos swapped
  blast_config/derived.c
  blast_config/tx_struct_tng.c
  mcp/commanding/commands.c
  mcp/include/actuators.h
  mcp/motors/actuators.c
  mcp/motors/tests/CMakeLists.txt
  mcp/motors/tests/test_el_lock.c
  mcp/pointing/pointing.c
  mcp/sensors/star_camera_transmit.c
Labels: bug, PREFLIGHT-MUSTFIX

#105 PSS resurrection
  .github/workflows/build-ground-software.yml
  blast_config/command_list.c
  blast_config/include/command_list.h
  blast_config/tx_struct_tng.c
  groundhog/CMakeLists.txt
  mcp/CMakeLists.txt
  mcp/commanding/commands.c
  mcp/housekeeping/sensor_updates.c
  mcp/include/command_struct.h
  mcp/include/pointing.h
  mcp/include/pointing_struct.h
  mcp/mcp.c
  mcp/pointing/pointing.c
  mcp/sensors/acs.c
Labels: PREFLIGHT-MUSTFIX

#106 Feature: reset latched faults on command
  blast_config/command_list.c
  mcp/commanding/commands.c
  mcp/include/ec_motors.h
  mcp/motors/ec_motors.c
Labels: enhancement

#107 Enable in-flight changes of the ethercat motor latching fault mask
  blast_config/command_list.c
  blast_config/derived.c
  blast_config/include/command_list.h
  blast_config/tx_struct_tng.c
  mcp/commanding/commands.c
  mcp/include/ec_motors.h
  mcp/include/motors.h
  mcp/motors/ec_motors.c
  mcp/motors/motors.c
Labels: enhancement

#110 Remap relay controls for TIM FTS test flight
  blast_config/command_list.c
  blast_config/include/command_list.h
  blast_config/tx_struct_tng.c
  mcp/commanding/commands.c
  mcp/housekeeping/inner_frame_power.c
  mcp/housekeeping/motor_box_power.c
  mcp/housekeeping/outer_frame_power.c
  mcp/include/inner_frame_power.h
  mcp/include/motor_box_power.h
  mcp/include/outer_frame_power.h
  mcp/motors/actuators.c
Labels: documentation, enhancement, PREFLIGHT-MUSTFIX

#116 Updates from telemetry debugging and el axis test
  blast_config/command_list.c
  blast_config/include/calibrate.h
  blast_config/linklists/test.ll
  blast_config/tx_struct_tng.c
  blast_etc/hosts/hosts_fc1
  blast_etc/hosts/hosts_fc2
  blast_etc/udev/91-serial.rules
  kst/tim/gyros.kst
  kst/tim/pinhole_sun_sensors.kst
  kst/tim/power_system.kst
  mcp/commanding/commands.c
  mcp/communications/tests/test_evtm.c
  mcp/housekeeping/motor_box_power.c
  mcp/include/inclinometer.h
  mcp/include/motor_box_power.h
  mcp/include/motors.h
  mcp/mcp.c
  scripts/uploading/upload_etc.sh
  scripts/uploading/upload_linklists.sh
Labels: enhancement, PREFLIGHT-MUSTFIX

#117 Hard Drive diskmanager.c: Auto-Standby & TIM FTS 2024
  mcp/diskmanager/diskmanager_tng.c
Labels: bug, enhancement, PREFLIGHT-MUSTFIX

#120 Debugging thermistor telemetry, kst/owl files, and some pointing debugging updates
  blast_config/command_list.c
  blast_config/derived.c
  blast_config/linklists/old/M2Actuators.ll
  blast_config/linklists/old/aalborgs.ll
  blast_config/linklists/old/az_check_light.ll
  blast_config/linklists/old/balance_system.ll
  blast_config/linklists/old/coarse_sensor_monitoring.ll
  blast_config/linklists/old/cryo_important.ll
  blast_config/linklists/old/cryovalves.ll
  blast_config/linklists/old/gps_status.ll
  blast_config/linklists/old/hwpr.ll
  blast_config/linklists/old/lock.ll
  blast_config/linklists/old/magnetometer.ll
  blast_config/linklists/old/motor_debugging.ll
  blast_config/linklists/old/motor_tests_small.ll
  blast_config/linklists/old/paul_therm.ll
  blast_config/linklists/old/pbob.ll
  blast_config/linklists/old/power_system.ll
  blast_config/linklists/old/pss_debugging.ll
  blast_config/linklists/old/pss_essential.ll
  blast_config/linklists/old/pss_pointing.ll
  blast_config/linklists/old/roachSBD.ll
  blast_config/linklists/old/roach_noise_psd.ll
  blast_config/linklists/old/roach_status.ll
  blast_config/linklists/old/shutter.ll
  blast_config/linklists/old/starcams.ll
  blast_config/linklists/old/steppers.ll
  blast_config/linklists/old/steppers_essential.ll
  blast_config/linklists/old/test2.ll
  blast_config/linklists/old/test3.ll
  blast_config/linklists/old/test4.ll
  blast_config/linklists/old/test_files.ll
  blast_config/linklists/old/thermistors.ll
  blast_config/linklists/shared.ll
  blast_etc/thermistor_R_to_T_TIM.LUT
  blast_etc/thermistor_R_to_T_TIM.lut
  blast_etc/thermistor_V_to_R_TIM.LUT
  blast_etc/thermistor_V_to_R_TIM.lut
  kst/tim/core_pos_time_mcp.kst
  kst/tim/dgps.kst
  kst/tim/elevation.kst
  kst/tim/gyros.kst
  kst/tim/power_system.kst
  kst/tim/reaction_wheel.kst
  kst/tim/thermistors.kst
  mcp/include/motors.h
  mcp/pointing/pointing.c
  owl/PAbstractDataItem.cpp
  owl/PMainWindow.cpp
  owl/main.cpp
  owl/owl-files/tim/tim2024.owl
  owl/owl.pro
  scripts/ground_station/upload_etc.sh
  scripts/uploading/upload_etc.sh
Labels: bug, Code Cleanup

#123 New feature: add loop timing telemetry
  blast_config/linklists/sbd.ll
  blast_config/linklists/shared.ll
  blast_config/tx_struct_tng.c
  common/channels_tng.c
  common/include/channels_tng.h
  kst/tim/core_pos_time_mcp.kst
  kst/tim/elevation.kst
  kst/tim/gyros.kst
  kst/tim/hard_disks.kst
  kst/tim/pinhole_sun_sensors.kst
  kst/tim/power_system.kst
  kst/tim/reaction_wheel.kst
  kst/tim/thermistors.kst
  mcp/diskmanager/diskmanager_tng.c
  mcp/housekeeping/CMakeLists.txt
  mcp/housekeeping/loop_timing.c
  mcp/include/loop_timing.h
  mcp/mcp.c
  mcp/sensors/csbf_dgps.c
  mcp/sensors/star_camera_transmit.c
  mcp/sensors/star_camera_trigger.c
  scripts/building/build_mcp.sh
  scripts/uploading/upload_linklists.sh
Labels: enhancement
